### ISSUE TITLE
Practitioner profile - sec 17.12.1.4 Practitioner Qualifications - update to text needed

### ISSUE THREAD

**Issue by daniel-thomson** [HL7NZ/hpi#8]
Update to the text in this section needed: https://build.fhir.org/ig/HL7NZ/hpi/StructureDefinition-HpiPractitioner.html#practitioner-qualifications

Current text includes this sentence "After some discussion, it was decided that only ‘registration’ information is to be included in the Practitioner resource to avoid confusion. This can be revisited if needed." 

Maybe just needs deleting - as it looks like we've decided to include educational qualification info in the resource

**Comment by davidhay25** [comment]
deleted
